# Generated by Django 4.2.7 on 2025-10-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Elemento')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('mobiliario', 'Mobiliario'), ('tecnologia', 'Tecnología'), ('decoracion', 'Decoración'), ('audio', 'Audio y Sonido'), ('iluminacion', 'Iluminación'), ('otro', 'Otro')], max_length=50, verbose_name='Categoría')),
                ('stock_total', models.IntegerField(verbose_name='Stock Total')),
                ('stock_disponible', models.IntegerField(verbose_name='Stock Disponible')),
                ('unidad_medida', models.CharField(default='unidad', max_length=20, verbose_name='Unidad de Medida')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('mantenimiento', 'En Mantenimiento'), ('dado_baja', 'Dado de Baja')], default='disponible', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Elemento',
                'verbose_name_plural': 'Elementos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='elemento',
            constraint=models.CheckConstraint(check=models.Q(('stock_disponible__lte', models.F('stock_total'))), name='stock_disponible_no_mayor_que_total'),
        ),
        migrations.AddConstraint(
            model_name='elemento',
            constraint=models.CheckConstraint(check=models.Q(('stock_disponible__gte', 0)), name='stock_disponible_no_negativo'),
        ),
    ]
