# Generated by Django 4.2.7 on 2025-10-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Espacio')),
                ('tipo', models.CharField(choices=[('salon', 'Salón'), ('patio', 'Patio'), ('hall', 'Hall'), ('laboratorio', 'Laboratorio'), ('auditorio', 'Auditorio'), ('cancha', 'Cancha Deportiva'), ('otro', 'Otro')], max_length=50, verbose_name='Tipo de Espacio')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad (personas)')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('caracteristicas', models.JSONField(blank=True, default=dict, verbose_name='Características')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('mantenimiento', 'En Mantenimiento'), ('bloqueado', 'Bloqueado')], default='disponible', max_length=20, verbose_name='Estado')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible para Reservas')),
            ],
            options={
                'verbose_name': 'Espacio',
                'verbose_name_plural': 'Espacios',
                'ordering': ['nombre'],
            },
        ),
    ]
