# Generated by Django 5.2.6 on 2025-12-12 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carrera', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Carrera')),
                ('codigo', models.TextField(blank=True, max_length=20, null=True, verbose_name='Código de la Carrera')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Área Académica')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['nombre_carrera'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='usuarios.carrera', verbose_name='Carrera'),
        ),
    ]
