# Generated by Django 4.2.7 on 2025-10-24 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('APPROVE', 'Aprobar'), ('REJECT', 'Rechazar')], max_length=50, verbose_name='Acción')),
                ('tabla_afectada', models.CharField(max_length=50, verbose_name='Tabla Afectada')),
                ('registro_id', models.IntegerField(blank=True, null=True, verbose_name='ID del Registro')),
                ('valores_previos', models.JSONField(blank=True, null=True, verbose_name='Valores Anteriores')),
                ('valores_nuevos', models.JSONField(blank=True, null=True, verbose_name='Valores Nuevos')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origen')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-timestamp'],
            },
        ),
    ]
